### ISSUE TITLE
[contract] use a nothing-up-my-sleeve zero value for the Merkle tree contract

### ISSUE THREAD

**Issue by weijiekoh** [barryWhiteHat/maci#35]

**Comment by barryWhiteHat** [comment]
I'm not sure we should use a nothing up my sleave value for merkle tree. Because originally everything in the merkle tree needs to be known. So we should initalize it to be an empty tree. Or am i missing something?

**Comment by weijiekoh** [comment]
I think when I proposed this, I was thinking along the lines that we should use the audited Merkle Tree code from Semaphore instead. And that uses a nothing-up-my-sleeve value. Perhaps this issue should be renamed to "Use the audited Merkle Tree contract from Semaphore" instead.

**Comment by barryWhiteHat** [comment]
OH yeah you are right. As long as the ntohing up my sleve value i known this is the same as using zeroed leaves. In fact its better because we can make a trust argument about it.
