### ISSUE TITLE
Build coordinator logic

### ISSUE THREAD

**Issue by barryWhiteHat** [barryWhiteHat/maci#6]
Operator needs to create proofs from the encrhpted signatures in teh smart contract in the smart contract. 

They should also be able to reveal the vote count. 

The logic to create these proofs and broadcast them needs to be implemented.

**Comment by weijiekoh** [comment]
May I suggest that we close this issue, as long as #3, #4, and #5, so that the issues page doesn't overlap project trajectory that @kendricktan and I are currently on?

We are using this for project management: https://github.com/barryWhiteHat/maci/projects/1
